
---
kind: pipeline
type: docker
name: Build

trigger:
  event:
    - push
    - custom

steps:
  - name: Build & Upload
    image: ubuntu:22.04
    commands:
      - sudo apt update && sudo apt install libgmp-dev libmpfr-dev libmpc-dev gcc-multilib
      - bash build.sh
    environment:
      GITEA_ENDPOINT: https://git.m.ac
      GITEA_USER: baoshuo
      GITEA_TOKEN:
        from_secret: GITEA_TOKEN
